# Automatically generated by configure - do not modify
SRC_PATH=/home/josh/Downloads/ucc/roms/vgabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/josh/sdb2/Lab/PQEMU/roms/vgabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
